/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyzk_myndk_MyNative */

#ifndef _Included_com_zyzk_myndk_MyNative
#define _Included_com_zyzk_myndk_MyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyzk_myndk_MyNative
 * Method:    myjni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zyzk_myndk_MyNative_myjni
  (JNIEnv *env, jclass job){
 return (*env)->NewStringUTF(env, "This is My First JNI");
}
#ifdef __cplusplus
}
#endif
#endif
//
// Created by Admin on 2018/1/10.
//

